image: tandukion/ci-runner:test
variables:
  ROS_PACKAGES_TO_INSTALL: ""

cache:
  paths:
    - ccache/

before_script:
 - git clone https://gitlab.com/VictorLamoine/ros_gitlab_ci.git
 - source ros_gitlab_ci/gitlab-ci.bash >/dev/null
 - apt-get install -y python-dev python-pip
 - pip install transitions

catkin_make:
  stage: build
  artifacts:
    paths:
      - build.tar
    expire_in: 1 day
  script:
    - catkin_make
    - tar cf build.tar build devel

catkin_make tests:
  stage: test
  script:
    - tar xf build.tar
    - source devel/setup.bash
    - catkin_make run_tests
    - catkin_make test

