image: tandukion/ci-runner:test
variables:
  ROS_PACKAGES_TO_INSTALL: ""

cache:
  paths:
    - ccache/

before_script:
 - git clone https://gitlab.com/VictorLamoine/ros_gitlab_ci.git
 - source ros_gitlab_ci/gitlab-ci.bash >/dev/null
 - apt-get install -y python-dev python-pip
 - pip install transitions

 # cache
 - mkdir -p ccache
 - export CCACHE_BASEDIR=${PWD}
 - export CCACHE_DIR=${PWD}/ccache
 - export PATH=/usr/lib/ccache:$PATH

catkin_make:
  stage: build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/build.tar
    expire_in: 1 day
  script:
    - catkin_make
    - tar cf $CI_PROJECT_DIR/build.tar build devel

catkin_make tests:
  stage: test
  script:
    - tar xf $CI_PROJECT_DIR/build.tar -C $PWD
    - source devel/setup.bash
    - catkin_make run_tests
    - catkin_make test

