image: ros:kinetic-robot

variables:
  ROS_PACKAGES_TO_INSTALL: ""

cache:
  paths:
    - ccache/

before_script:
 - git clone https://gitlab.com/VictorLamoine/ros_gitlab_ci.git
 - source ros_gitlab_ci/gitlab-ci.bash >/dev/null
 - apt-get install -y python-dev python-pip
 - pip install -r requirements.txt

catkin_make tests:
  stage: test
  script:
    - catkin_make
    - catkin_make run_tests
    - catkin_make test

