name: ROS CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    env:
      ROS_DISTRO: kinetic

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive
          
    - name: Install ROS
      run: |
        sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
        sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
        sudo apt-get -qq update -y
        sudo apt-get -qq install -y ros-$ROS_DISTRO-desktop
        sudo apt-get -qq install -y python-rosinstall python-rosinstall-generator python-wstool build-essential
        sudo apt-get -qq install -y ros-$ROS_DISTRO-catkin python-catkin-tools        
        sudo rosdep init
        rosdep update
        
    - name: Install ROS package
      run: |
        sudo apt-get -qq install -y ros-$ROS_DISTRO-moveit
        sudo apt-get -qq install -y ros-$ROS_DISTRO-industrial-core
        sudo apt-get -qq install -y ros-$ROS_DISTRO-timed-roslaunch
        sudo apt-get -qq install -y ros-$ROS_DISTRO-rosbridge-server
        sudo apt-get -qq install -y ros-$ROS_DISTRO-tf2-web-republisher

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Installing additional python packages requirements on submodules by creating list of "requirements.txt"
        REQ=($(find | grep "requirements.txt")) || true
        for req in ${REQ[@]}; do echo "Installing requirements from $req" && pip install -r $req; done

        # Installing additional apt packages
        PACK=($(find | grep "packages.txt")) || true
        for pack in ${PACK[@]}; do echo "Installing packages from $pack" && cat $pack | xargs apt-get -qq install -y; done

    - name: catkin_make
      run: |
        source /opt/ros/$ROS_DISTRO/setup.bash
        catkin_make
      
    - name: rostest
      run: |
        source /opt/ros/$ROS_DISTRO/setup.bash
        source devel/setup.bash
        catkin_make run_tests
        catkin_test_results
