name: ROS CI (docker)

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    container:
      image: tandukion/ci-runner:test
    env:
      ROS_DISTRO: kinetic

    steps:
    - uses: actions/checkout@v1

    - name: Checkout submodules
      shell: bash -e {0}
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive

    - name: Install dependencies
      shell: bash -e {0}
      run: |
        # Get into docker container
        /usr/bin/docker run -i -w $(pwd) -v $(pwd):$(pwd) tandukion/ci-runner:test

        # Installing additional python packages requirements on submodules by creating list of "requirements.txt"
        REQ=($(find | grep "requirements.txt")) || true
        for req in ${REQ[@]}; do echo "Installing requirements from $req" && pip install -r $req; done

        # Installing additional apt packages
        PACK=($(find | grep "packages.txt")) || true
        for pack in ${PACK[@]}; do echo "Installing packages from $pack" && cat $pack | xargs apt-get -qq install -y; done

    - name: catkin_make
      shell: bash -e {0}
      run: |
        catkin_make
      
    - name: rostest
      shell: bash -e {0}
      run: |
        source devel/setup.bash
        catkin_make run_tests
        catkin_test_results
