name: ROS CI (docker)

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    container: tandukion/ci-runner:test
    env:
      ROS_DISTRO: kinetic

    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive

    - name: Install dependencies
      run: |
        REQ=($(find | grep "requirements.txt")) || true
        for req in ${REQ[@]}; do echo "Installing requirements from $req" && pip install -r $req; done

        PACK=($(find | grep "packages.txt")) || true
        for pack in ${PACK[@]}; do echo "Installing packages from $pack" && cat $pack | xargs apt-get -qq install -y; done

    - name: catkin_make
      run: |
        catkin_make
      
    - name: rostest
      run: |
        source devel/setup.bash
        catkin_make run_tests
        catkin_test_results
